# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.9

    environment: GO111MODULE=on
    working_directory: /go/src/github.com/scribd/vaulttest
    steps:
      - checkout
      - run: wget https://releases.hashicorp.com/vault/1.2.3/vault_1.2.3_linux_amd64.zip
      - run: unzip vault*.zip
      - run: sudo cp vault /usr/local/bin/vault
      - run: go test -v ./...
